### ISSUE TITLE
Error "Argument of `file` function cannot be null"   

### ISSUE THREAD

**Issue by Tcvalenzuela** [cgroza/GraffiTE#4]
Hi

We are trying to run the pipeline but after giving the arguments:

`nextflow run cgroza/GraffiTE --assemblies SeaTurtles.csv --TE_library /srv/public/users/tomas/STR/rDerCor1/Checking_11_21/RepeatModeller2/rDerCor1_database2-families.fa --reference /srv/public/users/tomas/STR/rDerCor1/Checking_11_21/RepeatModeller2/rDerCor1.pri.cur.20210524.fasta --reads Reads.csv --cores 40`

or

`nextflow run /srv/public/users/tomas/programs/GraffiTE/main.nf --assemblies SeaTurtles.csv --TE_library /srv/public/users/tomas/STR/rDerCor1/Checking_11_21/RepeatModeller2/rDerCor1_database2-families.fa --reference /srv/public/users/tomas/STR/rDerCor1/Checking_11_21/RepeatModeller2/rDerCor1.pri.cur.20210524.fasta --reads Reads.csv --cores 40`

We have the error:
`Argument of `file` function cannot be null

 -- Check script '/srv/public/users/tomas/programs/GraffiTE/main.nf' at line: 59 or see '.nextflow.log' file for more details
Argument of `file` function cannot be null
`
checking on the `.nextflow.log`
```
Nov-08 11:38:02.199 [Actor Thread 4] ERROR nextflow.extension.OperatorImpl - @unknown
java.lang.IllegalArgumentException: Argument of `file` function cannot be null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at nextflow.Nextflow.file(Nextflow.groovy:146)
	at nextflow.Nextflow$file.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
	at Script_1fa1c3aa$_runScript_closure2.doCall(Script_1fa1c3aa:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.extension.MapOp$_apply_closure1.doCall(MapOp.groovy:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
	at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
	at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
	at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
	at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
	at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Nov-08 11:38:02.273 [Actor Thread 4] DEBUG nextflow.Session - Session aborted -- Cause: Argument of `file` function cannot be null
```
I have no idea what seems to be wrong help please :)

**Comment by cgroza** [comment]
May we see the contents of `SeaTurtles.csv`?

**Comment by Tcvalenzuela** [comment]
I tried to copy the example, do I need a header?
```
(base) tomas@yangtze:/srv/public/users/tomas/STR/GraffiTE$ cat SeaTurtles.csv
/srv/public/users/tomas/rCheMyd1/rCheMyd1_20210528/rCheMyd1.pri.cur.20210528.fasta,sampleA_CheMyd
/srv/public/users/tomas/rDerCor1/rDerCor1_20210524/rDerCor1.pri.cur.20210524.fasta,sampleB_DerCor
(base) tomas@yangtze:/srv/public/users/tomas/STR/GraffiTE$ cat Reads.csv 
/srv/public/users/tomas/rDerCor1/10x/rDerCor1_S1.fastq,sampleB_DerCor
/srv/public/users/tomas/rCheMyd1/10x/rCheMyd1_S1.fastq,sampleA_CheMyd
```

**Comment by cgroza** [comment]
Yes, please refer to https://github.com/cgroza/GraffiTE#parameters

This is an unfortunate effect of using the nextflow CSV parser. We access these fields by name and they return nil when they are not defined as a header.

**Comment by Tcvalenzuela** [comment]
Hahaha I thought that it was an example the sort of annotation or what should be there, I'll and report back thanks
